running !!!
Try to connect
Subscribing to: :#:
Process Started
Type command (exit) to exit.
>>> Traceback (most recent call last):
  File "mqtt_csv_logger.py", line 164, in <module>
    main(sys.argv[1:]) 
  File "mqtt_csv_logger.py", line 146, in main
    run_processes(db_name,g_params)
  File "mqtt_csv_logger.py", line 120, in run_processes
    userInput = raw_input(">>> ")
IOError: [Errno 9] Bad file descriptor
